# Generated by Django 5.2.6 on 2025-09-18 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserColorScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "primary_color",
                    models.CharField(
                        help_text="Hex color code (e.g., #FF0000)", max_length=7
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(help_text="Hex color code", max_length=7),
                ),
                (
                    "accent_color",
                    models.CharField(help_text="Hex color code", max_length=7),
                ),
                (
                    "muted_color",
                    models.CharField(help_text="Hex color code", max_length=7),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#FFFFFF", help_text="Hex color code", max_length=7
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        default="#000000", help_text="Hex color code", max_length=7
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_color_schemes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("user", "slug")},
            },
        ),
    ]
