# Generated by Django 5.2.13 on 2026-04-09 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="e.g., demographic_breakthrough", unique=True
                    ),
                ),
                ("text", models.TextField()),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., Data Scientist & Software Engineer",
                        max_length=200,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=30)),
                ("website", models.URLField(blank=True)),
                (
                    "location",
                    models.CharField(help_text="e.g., Austin, TX", max_length=100),
                ),
                (
                    "location_display",
                    models.CharField(
                        blank=True,
                        help_text="Display version with coordinates, e.g., Austin, TX (30.2672°N, 97.7431°W)",
                        max_length=200,
                    ),
                ),
                (
                    "slogan",
                    models.CharField(
                        blank=True, help_text="Tagline shown in header", max_length=300
                    ),
                ),
            ],
            options={
                "verbose_name": "Personal Info",
                "verbose_name_plural": "Personal Info",
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                (
                    "dates",
                    models.CharField(
                        help_text="e.g., 2021 - 2023 or 2005 - Present", max_length=100
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Data Science & Political Analytics",
                        max_length=300,
                    ),
                ),
                ("is_current", models.BooleanField(default=False)),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower = appears first (most recent)"
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("dates", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField()),
                ("impact", models.TextField(blank=True)),
                ("technical_description", models.TextField(blank=True)),
                ("business_description", models.TextField(blank=True)),
                ("spatial_description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Skill Categories",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTechnology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technologies",
                        to="portfolio.project",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Project Technologies",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Responsibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Full version (used in electoral archetypes)"
                    ),
                ),
                (
                    "text_neutral",
                    models.TextField(
                        blank=True,
                        help_text="Neutral version (used in non-electoral archetypes). If blank, 'text' is used everywhere.",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsibilities",
                        to="portfolio.position",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Responsibilities",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Python, Pipelines", max_length=200
                    ),
                ),
                (
                    "detail",
                    models.TextField(
                        blank=True,
                        help_text="e.g., 20+ years: NumPy, Pandas, Scikit-learn...",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="portfolio.skillcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        help_text="e.g., LinkedIn, GitHub", max_length=100
                    ),
                ),
                ("url", models.URLField()),
                (
                    "display_text",
                    models.CharField(
                        blank=True,
                        help_text="Text shown on resume if different from URL",
                        max_length=200,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "personal_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="portfolio.personalinfo",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
    ]
