# Generated by Django 5.2.13 on 2026-04-09 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeArchetype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Shown on the public download form when this archetype is selected",
                    ),
                ),
                (
                    "is_electoral",
                    models.BooleanField(
                        default=False,
                        help_text="If True, uses electoral-specific responsibility text",
                    ),
                ),
                ("max_achievements", models.PositiveIntegerField(default=4)),
                (
                    "max_responsibilities_per_job",
                    models.PositiveIntegerField(default=3),
                ),
                (
                    "siege_analytics_max",
                    models.PositiveIntegerField(
                        default=6,
                        help_text="Max responsibilities for Siege Analytics position",
                    ),
                ),
                ("show_project_technical_details", models.BooleanField(default=True)),
                (
                    "competency_detail_level",
                    models.CharField(
                        choices=[
                            ("comprehensive", "Comprehensive"),
                            ("focused", "Focused"),
                            ("business_focused", "Business Focused"),
                        ],
                        default="focused",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProfessionalSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "archetype",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="portfolio.resumearchetype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Professional Summaries",
            },
        ),
        migrations.CreateModel(
            name="ResumeArchetypeAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.achievement",
                    ),
                ),
                (
                    "archetype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.resumearchetype",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "unique_together": {("archetype", "achievement")},
            },
        ),
        migrations.AddField(
            model_name="resumearchetype",
            name="achievements",
            field=models.ManyToManyField(
                blank=True,
                through="portfolio.ResumeArchetypeAchievement",
                to="portfolio.achievement",
            ),
        ),
        migrations.CreateModel(
            name="ResumeArchetypePosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "archetype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.resumearchetype",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.position",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "unique_together": {("archetype", "position")},
            },
        ),
        migrations.AddField(
            model_name="resumearchetype",
            name="positions",
            field=models.ManyToManyField(
                blank=True,
                through="portfolio.ResumeArchetypePosition",
                to="portfolio.position",
            ),
        ),
        migrations.CreateModel(
            name="ResumeArchetypeProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "archetype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.resumearchetype",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.project",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "unique_together": {("archetype", "project")},
            },
        ),
        migrations.AddField(
            model_name="resumearchetype",
            name="projects",
            field=models.ManyToManyField(
                blank=True,
                through="portfolio.ResumeArchetypeProject",
                to="portfolio.project",
            ),
        ),
        migrations.CreateModel(
            name="ResumeArchetypeSkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "archetype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.resumearchetype",
                    ),
                ),
                (
                    "skill_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.skillcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "unique_together": {("archetype", "skill_category")},
            },
        ),
        migrations.AddField(
            model_name="resumearchetype",
            name="skill_categories",
            field=models.ManyToManyField(
                blank=True,
                through="portfolio.ResumeArchetypeSkillCategory",
                to="portfolio.skillcategory",
            ),
        ),
    ]
