# Generated by Django 5.2.13 on 2026-04-09 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_resumearchetype_professionalsummary_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Generic recruiter intro", max_length=200
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "subject_template",
                    models.CharField(
                        help_text="Supports placeholders: {recipient_name}, {job_title}, {company}, {archetype_name}",
                        max_length=500,
                    ),
                ),
                (
                    "body_template",
                    models.TextField(
                        help_text="Supports placeholders: {recipient_name}, {job_title}, {company}, {archetype_name}, {your_name}"
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                (
                    "role",
                    models.CharField(
                        blank=True, help_text="e.g., Senior Recruiter", max_length=200
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "job_url",
                    models.URLField(blank=True, help_text="Link to the job posting"),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Senior Data Analyst (Databricks)",
                        max_length=300,
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("recruiter", "Recruiter"),
                            ("hiring_manager", "Hiring Manager"),
                            ("referral", "Referral"),
                            ("direct_application", "Direct Application"),
                        ],
                        default="recruiter",
                        max_length=20,
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="How you were introduced, context"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResumeInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., John Sanford — Databricks Senior Analyst",
                        max_length=300,
                    ),
                ),
                (
                    "summary_override",
                    models.TextField(
                        blank=True,
                        help_text="If set, replaces the archetype's professional summary for this instance",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archetype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="portfolio.resumearchetype",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instances",
                        to="portfolio.recipient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GenerationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archetype_slug",
                    models.CharField(
                        help_text="Archetype slug at time of generation", max_length=100
                    ),
                ),
                (
                    "format_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("docx", "DOCX"),
                            ("rtf", "RTF"),
                            ("md", "Markdown"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "output_type",
                    models.CharField(
                        choices=[("ats", "ATS-Optimized"), ("human", "Human-Readable")],
                        max_length=10,
                    ),
                ),
                ("color_scheme", models.CharField(max_length=100)),
                (
                    "length_variant",
                    models.CharField(
                        choices=[
                            ("long", "Long"),
                            ("short", "Short"),
                            ("brief", "Brief"),
                        ],
                        max_length=10,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("was_emailed", models.BooleanField(default=False)),
                (
                    "instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generations",
                        to="portfolio.resumeinstance",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
    ]
