# Generated by Django 5.2.13 on 2026-04-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_emailtemplate_recipient_resumeinstance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="business_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="spatial_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="project",
            name="technical_description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
