# Generated by Django 5.2.13 on 2026-04-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_alter_project_business_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalinfo",
            name="footer_text",
            field=models.CharField(
                blank=True,
                help_text="Footer text (HTML allowed). e.g., Built with <a href='...'>Django</a> and <a href='...'>ReportLab</a>",
                max_length=500,
            ),
        ),
    ]
