# Generated by Django 5.2.13 on 2026-04-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_personalinfo_footer_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalinfo",
            name="logo_url",
            field=models.URLField(
                blank=True, help_text="URL to logo/portrait image shown in hero section"
            ),
        ),
    ]
