# Generated by Django 5.2.13 on 2026-04-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_personalinfo_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeinstance',
            name='follow_up_date',
            field=models.DateField(blank=True, help_text='When to follow up on this send', null=True),
        ),
        migrations.AddField(
            model_name='resumeinstance',
            name='follow_up_notes',
            field=models.TextField(blank=True, help_text='Notes about the follow-up'),
        ),
        migrations.AddField(
            model_name='resumeinstance',
            name='follow_up_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('not_needed', 'Not Needed')], default='not_needed', max_length=20),
        ),
        migrations.AddField(
            model_name='resumeinstance',
            name='subject_override',
            field=models.CharField(blank=True, help_text="If set, replaces the email template's subject line for this instance", max_length=500),
        ),
    ]
